property:
  gpu-id: 0
  net-scale-factor: 0.01735207357279195
  offsets: 123.675;116.28;103.53
  model-color-format: 0
  onnx-file: /home/lab314/workspace/yolo_ds/models/resnet50_market1501_aicity156.onnx
  model-engine-file: /home/lab314/workspace/yolo_ds/models/resnet50_market1501_aicity156.onnx_b4_gpu0_fp16.engine
  infer-dims: 3;256;128
  batch-size: 1
  network-mode: 2
  network-type: 100
  interval: 10
  process-mode: 2
  # cluster-mode: 3
  classifier-threshold: 0
  output-tensor-meta: 1
  maintain-aspect-ratio: 0
  operate-on-class-ids: 0
  scaling-compute-hw: 1
  gie-unique-id: 2
